name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # 監聽 main 分支的 push 事件

jobs:
  ci-cd-process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 設置 Docker Buildx (提升構建效能與功能)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 登入 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 構建並推送
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # 這裡會觸發 Dockerfile 內的所有階段，包含測試
          target: final
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:${{ github.sha }}

